name: SSH deploy on push
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: rsync deploy
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: .
          remote_host: yc422543.ftp.tools
          remote_user: yc422543
          remote_key: Fobiya
          remote_path: /home/yc422543/uh-vpn.org/demo/
